-- =============================================================================
-- FoodPro — Complete Database Schema (PostgreSQL via Supabase)
-- =============================================================================
-- Entities: users, production_lines, batch_logs
-- Relationships:
--   users (1) ──→ (N) production_lines   (A user manages many production lines)
--   production_lines (1) ──→ (N) batch_logs  (A line produces many batch logs)
-- =============================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(trim(name)) > 0),
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'Operator',
    company TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Production Lines Table
CREATE TABLE IF NOT EXISTS production_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(trim(name)) > 0),
    status TEXT NOT NULL CHECK (status IN ('Running', 'Paused', 'Stopped')),
    progress INTEGER NOT NULL CHECK (progress >= 0 AND progress <= 100),
    temp TEXT NOT NULL CHECK (char_length(trim(temp)) > 0),
    assigned_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Batch Logs Table
CREATE TABLE IF NOT EXISTS batch_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_line_id BIGINT NOT NULL REFERENCES production_lines(id) ON DELETE CASCADE,
    batch_number TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('In Progress', 'Completed', 'Failed')),
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    notes TEXT DEFAULT ''
);

-- =============================================================================
-- Seed Data
-- =============================================================================

-- Users
INSERT INTO users (name, email, role, company) VALUES
('Ritik Choudhary', 'ritik@foodpro.com', 'Plant Manager', 'FoodPro Industries'),
('Vineet Choudhary', 'vineet@foodpro.com', 'Operator', 'FoodPro Industries'),
('Priya Sharma', 'priya@foodpro.com', 'Quality Analyst', 'FoodPro Industries')
ON CONFLICT (email) DO NOTHING;

-- Production Lines (with assigned_user_id linking to users)
-- NOTE: If production_lines already has data from the earlier setup,
-- the existing rows will remain. These inserts add new rows only if the table is fresh.
-- Use a DO block to conditionally insert:
DO $$
BEGIN
    IF (SELECT COUNT(*) FROM production_lines) = 0 THEN
        INSERT INTO production_lines (name, status, progress, temp, assigned_user_id) VALUES
        ('Line 1 — Dairy Processing', 'Running', 78, '4.2°C', 1),
        ('Line 3 — Beverage Mixing', 'Paused', 45, '22.1°C', 2),
        ('Line 7 — Grain Milling', 'Running', 92, '28.5°C', 1),
        ('Line 9 — Meat Packaging', 'Running', 61, '-2.1°C', 3),
        ('Line 12 — Snack Production', 'Running', 34, '35.0°C', 2);
    END IF;
END $$;

-- Batch Logs
INSERT INTO batch_logs (production_line_id, batch_number, status, started_at, completed_at, notes) VALUES
(1, 'BATCH-4720', 'Completed', NOW() - INTERVAL '3 hours', NOW() - INTERVAL '1 hour', 'Quality check passed.'),
(1, 'BATCH-4721', 'Completed', NOW() - INTERVAL '50 minutes', NOW() - INTERVAL '2 minutes', 'Batch completed successfully.'),
(3, 'BATCH-1102', 'In Progress', NOW() - INTERVAL '30 minutes', NULL, 'Grain milling in progress.'),
(4, 'BATCH-0087', 'Completed', NOW() - INTERVAL '5 hours', NOW() - INTERVAL '3 hours', 'Meat packaging complete. Stored at -2.1°C.'),
(5, 'BATCH-0553', 'Failed', NOW() - INTERVAL '2 hours', NOW() - INTERVAL '90 minutes', 'Temperature exceeded safe threshold. Batch discarded.');
